'use client'
import React from "react";
import Breadscrumb from "@/app/components/common/breadscrumb/Breadscrumb";
import { Table, Collapse } from "antd";

const { Panel } = Collapse;

const breadcrumbItems: any = [
  { label: "Home", href: "/" },
  { label: "Products", href: "/products" },
];

const productsData = [
  {
    category: "HARMONAL ORAL AND INJECTABLE DRUGS",
    products: [
      { id: 1, product: "FERROUS FUMARATE +FOLIC ACID, ZINC SULPHATE MONOHYDRATE TABLET", strength: "152mg+750mcg+61.8mg" },
      { id: 2, product: "MESTEROLONE 25 TABLET", strength: "25mg" },
      { id: 3, product: "PROCHLORPERAZINE MALEATE TABLET", strength: "5mg" },
      { id: 4, product: "L-ARGININE, UBIDECARENONE+ ZINC SULPHATE MONOHYDRATE + LYCOPENE + FOLIC ACID+ SELENIUM CAPSULE", strength: "100mg+ 100mg+11mg+3000mcg+100mcg+40mcg" },
      { id: 5, product: "FOLIC ACID TABLET", strength: "5/10mg" },
      { id: 6, product: "ATOSIBAN ACETATE SOLUTION(INJ)", strength: "7.5mg/ml" },
    ]
  },
  {
    category: "ANTI DIABETICS ORAL DRUGS",
    products: [
      { id: 1, product: "VOGLIBOSE TABLET", strength: "0.2/0.3mg" },
      { id: 2, product: "PIOGLITAZONE TABLET", strength: "15/30/45mg" },
      { id: 3, product: "GLIMEPIRIDE TABLET", strength: "1/2/3/4mg" },
      { id: 4, product: "TENELIGLIPTIN TABLET", strength: "20mg" },
      { id: 5, product: "METFORMIN HCL (SR) TABLET", strength: "500/750/850/1000mg" },
      { id: 6, product: "GLICLAZIDE+PIOLITAZONE+HCL (SR) TABLET", strength: "1/2mg+15mg+500mg" },
      { id: 7, product: "GLIMEPIRIDE+METFORMIN HCL (SR) TABLET", strength: "1/2mg +500mg" },
      { id: 8, product: "METFORMIN HCL (SR) TABLET", strength: "500/750/850/1000mg" },
      { id: 9, product: "METFORMIN HCL TABLET", strength: "500mg" },
      { id: 10, product: "PIOGLITAZONE+METFORMIN HCL (SR) TABLET", strength: "15mg+500mg" },
      { id: 11, product: "LANSOPRAZOLE DT (ORANGE FLAVOR) TABLET", strength: "15/30mg" },
      { id: 12, product: "GLICLAZIDE TABLET", strength: "40/80mg" },
      { id: 13, product: "VOGLIBOSE+METFORMIN HCL (SR) TABLET", strength: "0.2/0.3mg+500mg" },
    ]
  },
  {
    category: "GASTRO RESISTANT AND INJECTABLE DRUGS",
    products: [
      { id: 1, product: "RABEPRAZOLE SODIUM (EC PELLETS)+ DOMPERIDONE (SR PELLETS) CAPSULE", strength: "20mg +30mg" },
      { id: 2, product: "LEVOSULPIRIDE TABLET", strength: "25/50/100mg" },
      { id: 3, product: "LACTULOSE CONCENTRATION SYRUP", strength: "10mg in 15 ml" },
      { id: 4, product: "BISACODYL TABLET", strength: "5mg" },
      { id: 5, product: "SODIUM PICOSULFATE TABLET", strength: "10mg" },
      { id: 6, product: "SODIUM PICOSULFATE SYRUP", strength: "5mg in 5 ml" },
      { id: 7, product: "OMEPRAZOLE LYO", strength: "40mg" },
      { id: 8, product: "LEVOSULPIRIDE (SR PELLETS) +RABIPRAZOLE + SODIUM (EC PELLETS) CAPSULE", strength: "75mg+20mg" },
      { id: 9, product: "LANSOPRAZOLE CAPSULE", strength: "15/30mg" },
      { id: 10, product: "ESOMEPRAZOLE SODIUM LYO", strength: "40mg" },
      { id: 11, product: "CHLORDIAZEPOXIDE+CLINDINIUM + BROMIDE TABLET", strength: "5 mg+2.5 mg" },
      { id: 12, product: "PANTOPRAZOLE SODIUM 40", strength: "40mg" },
      { id: 13, product: "RANITIDINE HCL AMPOULE INJ", strength: "25mg" },
      { id: 14, product: "LEVOCARNITINE LIQUID VIAL", strength: "2.0gm/100ml" },
      { id: 15, product: "LEVOCARNITINE LIQUID VIAL", strength: "1gm" },
    ]
  },
  {
    category: "CNS ORAL DRUGS",
    products: [
      { id: 1, product: "NAPROXEN, DOMPERIDONE TABLET", strength: "250/500mg, 10mg" },
      { id: 2, product: "AMANTADINE HCL TABLET", strength: "100mg" },
      { id: 3, product: "RIZATRIPTAN TABLET", strength: "5/10 mg" },
      { id: 4, product: "MODAFINIL TABLET", strength: "100/200 mg" },
      { id: 5, product: "PRAMIPEXOLE DIHYDROCHLORIDE TABLET", strength: "0.125/0.25/0.5 mg" },
      { id: 6, product: "AMANTADINE HCL CAPSULE", strength: "100 mg" },
      { id: 7, product: "PROPRANOLOL HCL (SR PELLETS) CAPSULE", strength: "40 mg" },
      { id: 8, product: "PRAMIPEXOLE DIHYDROCHLORIDE (ER) TABLET", strength: "0.375/0.75mg" },
      { id: 9, product: "PROCYCLIDINE HCL TABLET", strength: "2.5mg" },
      { id: 10, product: "TRIHEXYPHENIDYL HCL", strength: "2mg" },
      { id: 11, product: "FLUNARIZINE TABLET", strength: "5/10 mg" },
    ]
  },
  {
    category: "ANTI-VERTIGO",
    products: [
      { id: 1, product: "BETAHISTINE, DIHYDROCHLORIDE TABLET", strength: "8/16/24mg" },
      { id: 2, product: "CINNARIZINE+ DIMENHYDRINATE TABLET", strength: "20mg+40mg" },
    ]
  },
  {
    category: "ANTI FUNGAL INJECTABLE DRUGS",
    products: [
      { id: 1, product: "VORICONAZOLE LYO", strength: "200mg/vial" },
      { id: 2, product: "CASPOFUNGIN LYO", strength: "50mg/vial" },
      { id: 3, product: "CASPOFUNGIN LYO", strength: "70mg/vial" },
    ]
  },
  {
    category: "MUSCLE RELAXANT INJECTABLE DRUGS",
    products: [
      { id: 1, product: "SUGAMMADEX SODIUM SOLUTION", strength: "100mg" },
    ]
  },
  {
    category: "ONCO INJECTABLES",
    products: [
      { id: 1, product: "TOPOTECAN HYDROCHLORIDE INJECTION", strength: "1mg and 4 mg/vial" },
      { id: 2, product: "5-FLUOROURACIL INJECTION", strength: "250mg, 500mg, 1gm, 2.5gm" },
      { id: 3, product: "IRINOTECAN HYDROCHLORIDE INJECTION", strength: "40mg, 100mg" },
      { id: 4, product: "CYCLOPHOSPHAMIDE INJECTION", strength: "500mg, 1000mg" },
      { id: 5, product: "OXALIPLATIN INJECTION", strength: "50mg, 100mg" },
      { id: 6, product: "BORTEZOMIB INJECTION", strength: "2mg, 3.5mg" },
      { id: 7, product: "CARBOPLATIN INJECTION", strength: "50mg, 150mg, 450mg" },
      { id: 8, product: "ETOPOSIDE INJECTION", strength: "100mg/200mg/250mg/400mg/500mg/1000mg" },
      { id: 9, product: "PEMETREXED DISODIUM INJECTION", strength: "100mg, 500mg" },
      { id: 10, product: "BLEOMYCIN INJECTION", strength: "15U, 30U" },
      { id: 11, product: "FLUDARABINE INJECTION", strength: "50mg" },
      { id: 12, product: "ZOLEDRONIC ACID INJECTION", strength: "4mg" },
      { id: 13, product: "EPIRUBICIN HYDROCHLORIDE INJECTION", strength: "10mg, 50mg, 100mg" },
      { id: 14, product: "PACLITAXEL INJECTION", strength: "30mg, 100mg, 260mg, 300mg" },
      { id: 15, product: "LEUCOVORIN CALCIUM INJECTION", strength: "50mg, 100mg, 200mg, 350mg" },
      { id: 16, product: "VINBLASTINE SULFATE INJECTION", strength: "1mg/ml" },
      { id: 17, product: "DOCETAXEL INJECTION", strength: "20mg/ml) 20mg, 80mg, 120mg" },
      { id: 18, product: "CISPLATIN INJECTION", strength: "10mg, 50mg" },
      { id: 19, product: "DOXORUBICIN HYDROCHLORIDE INJECTION", strength: "10mg, 20mg, 50mg" },
      { id: 20, product: "GEMCITABINE HYDROCHLORIDE INJECTION", strength: "200mg, 1000mg" },
    ]
  },
  {
    category: "ONCO INJECTABLES & ORALS – PIPELINE & ONCO ORALS",
    products: [
      { id: 1, product: "MITOMYCIN INJECTION", strength: "5mg, 20mg, 40mg" },
      { id: 2, product: "MELPHALAN INJECTION", strength: "50mg" },
      { id: 3, product: "PAMIDRONATE DISODIUM INJECTION", strength: "30mg, 60mg, 90mg" },
      { id: 4, product: "VINORELBINE TARTRATE INJECTION", strength: "10mg/ml, 50mg/5ml" },
      { id: 5, product: "ANASTROZOLE TABLETS", strength: "1mg" },
      { id: 6, product: "HYDROXYUREA CAPSULES", strength: "200mg, 300mg, 400mg, 500mg" },
      { id: 7, product: "TOREMIFENE TABLETS", strength: "60mg" },
      { id: 8, product: "CAPECITABINE TABLETS", strength: "150mg,500mg" },
      { id: 9, product: "TAMOXIFEN CITRATE TABLETS", strength: "10mg, 20mg" },
      { id: 10, product: "ERLOTINIB TABLETS", strength: "100mg, 150mg" },
      { id: 11, product: "SUNITINIB CAPSULES", strength: "12.5mg, 25mg, 50mg" },
      { id: 12, product: "GEFITINIB TABLETS", strength: "250mg" },
      { id: 13, product: "SORAFENIB TABLETS", strength: "200mg" },
      { id: 14, product: "MELPHALAN TABLETS", strength: "2mg, 5mg" },
      { id: 15, product: "THALIDOMIDE CAPSULES", strength: "50mg, 100mg" },
      { id: 16, product: "MEGESTROL ACETATE TABLETS", strength: "20mg, 40mg" },
      { id: 17, product: "TEMOZOLOMIDE CAPSULES", strength: "5mg, 20mg, 100mg, 140mg, 180mg, 250mg" },
      { id: 18, product: "CYCLOPHOSPHAMIDE TABLETS", strength: "50mg" },
      { id: 19, product: "IMATINIB TABLETS", strength: "100mg,400mg" },
      { id: 20, product: "ETOPOSIDE TABLETS/CAPSULES", strength: "50mg,100mg" },
    ]
  },
   {
    category: "TABLETS & CAPSULES",
    products: [
      { id: 1, product: "Aceclofenac 100mg + Paracetamol 325mg", packing: "10*10 Blister" },
      { id: 2, product: "Aceclofenac 100mg + Paracetamol 325mg + Serratiopeptidase 15mg", packing: "10*10 Alu/Alu" },
      { id: 3, product: "Aceclofenac 100mg + Paracetamol 325mg + Chlorzoxazone 250mg", packing: "10*10 Alu/Alu" },
      { id: 4, product: "Azithromycin 250mg", packing: "10X6 Blister" },
      { id: 5, product: "Azithromycin 500mg", packing: "10*3 Blister" },
      { id: 6, product: "Azithromycin 500mg and lactobassilus tablet", packing: "10*3 Blister" },
      { id: 7, product: "Cefixime 100mg Dispersible Tablet", packing: "10*10 Alu/Alu" },
      { id: 8, product: "Cefixime 200mg Dispersible Tablet", packing: "10*10 Alu/Alu" },
      { id: 9, product: "Cefixime 200mg + Ofloxacin 200mg", packing: "10*10 Alu/Alu" },
      { id: 10, product: "Levocetirizine 5mg + Montelukast 10mg", packing: "10*10 Alu/Alu" },
      { id: 11, product: "Levocetirizine 5mg", packing: "10*10 Alu/Alu" },
      { id: 12, product: "Levocetirizine Hcl 5 mg + Ambroxol Hcl 75 mg", packing: "10*10 Alu/Alu" },
      { id: 13, product: "Pantoprazole 40mg + Domperidone SR 30mg Capsule", packing: "10*10 Alu/Alu" },
      { id: 14, product: "Rabeprazole 20 mg + Domperidone 30mg SR (Enteric Coated Pellets) Capsules", packing: "10*10 Alu/Alu" },
      { id: 15, product: "Amoxycillin 500mg + Potassium Clavulanate Acid 125mg", packing: "10*10 Alu/Alu" },
      { id: 16, product: "Ofloxacin 200 mg Tablet", packing: "10*10 Alu/Alu" },
      { id: 17, product: "Ofloxacin 200mg + Ornidazole 500mg (Special O2 Die)", packing: "10*10 Blister" },
      { id: 18, product: "Nimesulide 100mg + Paracetamol 325mg", packing: "20X10 Blister" },
      { id: 19, product: "Levofloxacin 500mg", packing: "10*10 Alu/Alu" },
      { id: 20, product: "Pantoprazole 40 mg Tablet", packing: "10*10 Alu/Alu" },
      { id: 21, product: "Deflazacort 6mg", packing: "10*10 Alu/Alu" },
      { id: 22, product: "Aceclofenac 100mg + Paracetamol 325 mg + Thiocolchicoside 4 mg", packing: "10*10 Alu/Alu" },
      { id: 23, product: "Thiocolchicoside 4 mg + Aceclofenac 100mg", packing: "10*10 Alu/Alu" },
      { id: 24, product: "Rabeprazole Sodium 20mg + Aceclofenac 200 mg SR (Enteric Coated Pellets)", packing: "10*10 Alu/Alu" },
      { id: 25, product: "Aceclofenac 100mg + Paracetamol 325mg + Phenylephrine hydrochloride 5mg + Cetirizine Hydrochloride 10mg + Caffeine 25mg", packing: "10*10 Blister" },
      { id: 26, product: "Aceclofenac 200mg SR Tablet", packing: "10*10 Alu/Alu" },
      { id: 27, product: "Aceclofenac IP 100mg + Drotaverine 80mg", packing: "10*10 Alu/Alu" },
      { id: 28, product: "N-Acetylcysteine 600 mg Chewable Tablet", packing: "10*1*10 Alu/Alu" },
      { id: 29, product: "S-Adenosyl-L-Methionine 200 mg", packing: "10*10 Alu/Alu" },
      { id: 30, product: "Albendazole 400mg Tablet", packing: "20*1 Blister" },
      { id: 31, product: "Albendazole 400mg + Ivermectin 6 mg", packing: "10*10*1 Alu/Alu" },
      { id: 32, product: "Alfuzosin 10 mg + Dutasteride 0.5mg (Er)", packing: "10*10 Alu/Alu" },
      { id: 33, product: "Fluconazole 150mg + Azithromycin 1Gm + Secnidazole 1Gm (Combikit)", packing: "10*1*4 Blister" },
      { id: 34, product: "Acotiamide 100 mg Tablets", packing: "10*10 Alu/Alu" },
      { id: 35, product: "Artemether I.P. 80mg & Lumefantrine I.P. 480mg", packing: "10*6 Alu/Alu" },
      { id: 36, product: "Terbinafine 250mg", packing: "10*7 Blister" },
      { id: 37, product: "Brivaracetam 50mg Tablets", packing: "10*10 Alu/Alu" },
      { id: 38, product: "Brivaracetam 100 mg Tablets", packing: "10*10 Alu/Alu" },
      { id: 39, product: "Bilastine 20 mg", packing: "10*10 Alu/Alu" },
      { id: 40, product: "Bilastine 20 mg + Montelukast 10 mg", packing: "10*10 Alu/Alu" },
      { id: 41, product: "Acebrophylline 100 mg Capsule", packing: "10*10 Alu/Alu" },
      { id: 42, product: "Acebrophylline 200mg (SR) Tablet", packing: "10*10 Alu/Alu" },
      { id: 43, product: "Acebrophylline 100mg + Acetylcysteine 600mg", packing: "10*10 Alu/Alu" },
      { id: 44, product: "Montelukast Sodium 10mg + Fexofenadine 120mg + Acebrophylline 200mg (SR)", packing: "10*10 Alu/Alu" },
      { id: 45, product: "Levocetirizine 5mg + Montelukast 10mg + Ambroxol Hcl 75mg", packing: "10*10 Alu/Alu" },
      { id: 46, product: "Montelukast Sodium 4mg + Levocetirizine Hci 2.5 mg", packing: "10*10 Alu/Alu" },
      { id: 47, product: "Cefixime 100mg + Ofloxacin 100mg Tablet", packing: "10*10 Alu/Alu" },
      { id: 48, product: "Cefixime 200mg + Sulbactum 150mg Tablet", packing: "10*10 Alu/Alu" },
      { id: 49, product: "Cefixime 200mg + Cloxacillin 500mg with lactobassilus Tablet", packing: "10*10 Alu/Alu" },
      { id: 50, product: "Cefixime 50mg", packing: "10*10 Alu/Alu" },
      { id: 51, product: "Cefixime 200 mg with Lactobassilus Tablet", packing: "10*10 Alu/Alu" },
      { id: 52, product: "Cefixime 200mg + Azithromycin 250mg (lacto bassilus 60Million Spores)", packing: "10*10 Alu/Alu" },
      { id: 53, product: "Cefixime 200mg + Potassium Clavulanate 125 mg", packing: "10*10 Alu/Alu" },
      { id: 54, product: "Myo Inositol 600 mg + Metformin 500SR Tablet", packing: "10*10 Alu/Alu" },
      { id: 55, product: "Calcium Carbonate 625 mg + Calcium 250 mg + Boron 1.5 mg + Folic Acid 300 to 176.47 mcg + Vitamin K27 45 Mcg + Calcitriol 0.25 Mcg", packing: "10*1*10 Soft-Gel" },
      { id: 56, product: "Calcitriol 0.25 Mcg + Calcium Carbonate 500mg + Zinc 7.5mg", packing: "3*10 Soft-Gel" },
      { id: 57, product: "Calcitriol 0.25Mcg + Calcium Carbonate 500mg + Zinc 7.5mg", packing: "10*10 Soft-Gel" },
      { id: 58, product: "Calcitrol + Calcium Sitrate + Magnisume Oxide + Zinc Sulphate + Monohydrate + Methlylcobalamin + L Methylfolate", packing: "10*1*10 Soft-Gel" },
      { id: 59, product: "Calcium Citrate maleate 250mg And Vitamin D3 100 Iu", packing: "30Tablet Bottle" },
      { id: 60, product: "Calcium Carbonate From An Organic Source (Oystershell) Calcium 500mg + Vitamin D3 250 Iu", packing: "10*15 Blister" },
      { id: 61, product: "Methylcobalamin 500Mcg + Eicosapentaenoic Acid 90mg + Docosahexaenoic Acid 60 mg + Folic Acid 1.5mg + Pyridoxine Hydrochloride 3mg Ascorbic Acid 100mg + Vitamin E Acetate 25+I.U. + Zinc Oxide Eq. To Elemental zinc 15mg + Selenium Dioxide", packing: "10*1*10 Soft-Gel" },
      { id: 62, product: "Dextromethorphan Hydrobromide 10mg + Phenylephirne Hydrochloride 5mg + Chlorpheniramine Maleate 2mg", packing: "10*10 Softgel" },
      { id: 63, product: "Clarithromycin 500 mg", packing: "10*1*10 Alu/Alu" },
      { id: 64, product: "Clindamycin 100 mg + Clotrimazole 200 mg Vaginal Softgel capsule", packing: "10*1*3 Softgel" },
      { id: 65, product: "Clindamycin 300 mg capsule", packing: "10*10 Alu/Alu" },
      { id: 66, product: "Ciprofloxacian 500 mg", packing: "10*10 Blister" },
      { id: 67, product: "Ciprofloxacian 500 mg + Tinidazole 600 mg", packing: "10*10 Blister" },
      { id: 68, product: "Deflazacort 30mg", packing: "10*10 Alu/Alu" },
      { id: 69, product: "Myo Inositol 550 mg + D-Chiro Inositol + Folic acid 3mg + Vitamin D3 10 Mcg, Chromium Picolinate 196 Mcg, Biotin 30 Mcg + N-Acetyl Cysteine 600mg", packing: "10*1*10 Alu/Alu" },
      { id: 70, product: "Cissus Quadrangularis + Calcium Citrate Maleate + Methylcobalamin", packing: "10*1*10 Alu/Alu" },
      { id: 71, product: "Cinnarzine 20mg + Domperidone 10mg", packing: "10*10 Alu/Alu" },
      { id: 72, product: "Citicoline Sodium 500 mg", packing: "10*10 Alu/Alu" },
      { id: 73, product: "Paracetamol 500mg + Phenylephrine Hcl 5mg + Caffeine 30 mg + Diphenhydramine Hcl 25mg", packing: "10*10 Blister" },
      { id: 74, product: "Nimesulide 100mg + Paracetamol 325mg + Phenylephrine 10mg + Caffeine 25mg", packing: "10*10 Blister" },
      { id: 75, product: "Etoricoxib 60mg + Thiocolchicoside 4mg", packing: "10*10 Alu/Alu" },
      { id: 76, product: "Cholecalciferol (D3) 60000 I.U. Chewable Tablet", packing: "10*1*4 Blister" },
      { id: 77, product: "Cholecalciferol 60000 I.U", packing: "10*1*4 Soft Gel" },
      { id: 78, product: "Dydrogesterone 10 mg", packing: "10*1*10 blister" },
      { id: 79, product: "Desloratadine 5 mg + Montelukast 10mg", packing: "10*10 Alu/Alu" },
      { id: 80, product: "Doxylamine Succinate 10mg + Pyridoxine 10mg + Folic Acid 2.5mg", packing: "10*10 Blister" },
      { id: 81, product: "Doxylamine Succinate 20mg + Pyridoxine Hydrochloride 10mg + Folic Acid 2.5mg", packing: "10*10 Blister" },
      { id: 82, product: "Doxofyline 400mg Tablet", packing: "10*10 Blister" },
      { id: 83, product: "Doxofylline 400 mg + Ambroxol Hydrochloride 30 mg", packing: "10*10 Alu/Alu" },
      { id: 84, product: "Doxycycline 100 mg + Lacto bassilus 5 Million Spores", packing: "10*10 Blister" },
      { id: 85, product: "Drotaverine Hydrochloride 80mg", packing: "10*10 Alu/Alu" },
      { id: 86, product: "Drotaverine Hcl 80mg + Mefenamic Acid 250mg", packing: "10*10 Blister" },
      { id: 87, product: "Diclofenac 50mg + Paracetamol 325mg + Chlorzoxazone Usp 250 mg", packing: "10*10 Blister" },
      { id: 88, product: "Diclofenac 50mg + Paracetamol 325mg", packing: "10*10 Blister" },
      { id: 89, product: "Diclofenac 50mg + Serratiopeptidase 10mg", packing: "10*10 Alu/Alu" },
      { id: 90, product: "Diclofenac 50mg + Paracetamol 325 mg + Serratiopeptidase 10mg", packing: "10*10 Alu/Alu" },
      { id: 91, product: "Rabeprozole Sodium 20 mg + Diclofenac Sodium 100 mg SR (Enteric Coated) Capsules", packing: "10*10 Alu/Alu" },
      { id: 92, product: "Dexlansoprazole 30mg (Delayed Release) Capsule", packing: "10*10 Alu/Alu" },
      { id: 93, product: "Ebastine 20mg Tablet", packing: "10*10 Alu/Alu" },
      { id: 94, product: "Esomeprazole 40mg Tablet", packing: "10*10 Alu/Alu" },
      { id: 95, product: "Esomeprazole 40 mg + Levosulpiride 75 mg Capsule", packing: "10*10 Strip" },
      { id: 96, product: "Esomeprazole 40 mg (With Sodium Bicarbonate as Buffer)", packing: "10*10 Strip" },
      { id: 97, product: "Esomeprazole 40mg + Domperidone 30mg Capsule", packing: "10*10 Alu/Alu" },
      { id: 98, product: "Clarithromycin Ip 500 mg + Esomeprazole 40 mg + Amoxicillin 750 mg HP kit", packing: "10*1*6 Alu/Alu" },
      { id: 99, product: "Etodolac 400 mg + Thiocolchicoside 4mg", packing: "10*10 Alu/Alu" },
      { id: 100, product: "Etodolac 400mg", packing: "10*10 Alu/Alu" },
      { id: 101, product: "Etodolac 600mg", packing: "10*10 Alu/Alu" },
      { id: 102, product: "Wheat Germ Oil 100mg + Omega 3 Fatty Acid 30mg + Vitamin E 400mg Soft gel", packing: "10*10 Soft-Gel" },
      { id: 103, product: "Etoricoxib 120mg", packing: "10*10 Alu/Alu" },
      { id: 104, product: "Etoricoxib 60mg + Paracetamol 325mg", packing: "10*10 Blister" },
      { id: 105, product: "Etoricoxib 90 mg", packing: "10*10 Alu/Alu" },
      { id: 106, product: "Clomifene 25mg Tablet", packing: "10*10 Alu/Alu" },
      { id: 107, product: "Clomifene 50mg Tablet", packing: "10*10 Alu/Alu" },
      { id: 108, product: "Hydroxyzine Hydrochloride 25mg", packing: "10*15 Blister" },
      { id: 109, product: "Fenticonazole 600mg Capsule", packing: "1 Capsule" },
      { id: 110, product: "Linezolid 600 mg Tablet", packing: "10*1*10 Alu/Alu" },
      { id: 111, product: "Flunarizine 10mg + Propranolol 40mg Tablet", packing: "10*10 Alu/Alu" },
      { id: 112, product: "Flunarizine 10mg Tablet", packing: "10*10 Alu/Alu" },
      { id: 113, product: "Fexofenadine Hydrochloride 120mg Tablet", packing: "10*10 Blister" },
      { id: 114, product: "Fexofenadine Hydrochloride 180mg Tablet", packing: "10*10 Blister" },
      { id: 115, product: "Phyllanthus Emblica Extract as Natural Vitamin C with Vitamin D3 & Zinc Chewable Tablets", packing: "10X10 Strip" },
      { id: 116, product: "Pantoprazole 40mg Ondansetron Hydrochloride I.P. 4mg", packing: "10*10 Alu/Alu" },
      { id: 117, product: "Pantoprazole 40 mg + Itopride 150 mg Capsule", packing: "10*10 Alu/Alu" },
      { id: 118, product: "Pantoprazole 40mg + Domperidone 10mg Capsule", packing: "10*10 Alu/Alu" },
      { id: 119, product: "Pantoprazole 40mg + Levosulpiride 75 mg Capsule", packing: "10*10 Alu/Alu" },
      { id: 120, product: "Ferrous Ascorbate eq. to Elemental Iron 100 mg + Folic Acid 1.5mg + Zinc 22.5mg Tablet (In Drug Formulations)", packing: "10*10 Alu/Alu" },
      { id: 121, product: "Piroxicam 20 mg MD tablet", packing: "10*10 Alu/Alu" },
      { id: 122, product: "Flupirtine Maleate 100 mg + Paracetamol 325 mg", packing: "10*10 Blister" },
      { id: 123, product: "Coenzyme Q10 100mg + L-Carnitine 50mg + L-Glutathione 10mg Eicosapentaenoc Acid 90mg + Docosahexaenoic Acid 60mg + Lycopene 8000Mcg + Selenium 70Mcg + Zinc Oxide 12.50mg", packing: "10*1*10 Alu/Alu" },
      { id: 124, product: "Multivitamin + Multimineral + Antioxidant Capsule", packing: "10*10 Alu/Alu" },
      { id: 125, product: "Multivitamin + Multimineral + Antioxidant + Grape Seed Extract", packing: "10*15 Alu/Alu" },
      { id: 126, product: "Febuxostat 40 mg", packing: "10*10 Alu/Alu" },
      { id: 127, product: "Flupentixol Hydrochloride + Melitracen Hydrochloride Tablet", packing: "10*10 Blister" },
      { id: 128, product: "Fluconazole 150mg", packing: "10*5*2 Blister" },
      { id: 129, product: "Fluconazole 400mg", packing: "10*5*1 Alu/Alu" },
      { id: 130, product: "Cefuroxime 250mg + Potassium Clavulanate 125mg", packing: "10*1*10 Alu/Alu" },
      { id: 131, product: "Cefuroxime 500 mg + Potassium Clavulanate 125 mg", packing: "10*1*10 Alu/Alu" },
      { id: 132, product: "Cefuroxime Axetil 250 mg", packing: "10*1*6 Alu/Alu" },
      { id: 133, product: "Cefuroxime 500 Axetil mg", packing: "10*1*6 Alu/Alu" },
      { id: 134, product: "Cefuroxime 500 Axetil mg", packing: "10*10 Alu/Alu" },
      { id: 135, product: "Nitrofurantoin 100 mg Tablet", packing: "10*10 Alu/Alu" },
      { id: 136, product: "Pirfenidone 200 mg", packing: "10*10 Blister" },
      { id: 137, product: "Energy 0.152 Kcal + Carbohydrate 0.03 Gm + Protine 0.008 Gm + Fat 0.00 Gm + Lactobacillus 1.33 Billion Spores + Lactobacillus Rhamnosus 0.72 Billion Spores + Saccharomyces Boulardii 0.50 Billion Spores + Bifidobachterium Longum 0.20 Billion Spores + Fructo Oligosaccharides 100 mg", packing: "10*10 Alu/Alu" },
      { id: 138, product: "Flaxseed Oil Omega 3,6,9 Softgel", packing: "10*10 Soft-Gel" },
      { id: 139, product: "Omeprazole 20mg", packing: "10*10 Strip" },
      { id: 140, product: "Omeprazole 20mg + Domperidone 10mg", packing: "20*15 Strip" },
      { id: 141, product: "Gabapentin 400 mg + Nortriptyline Hydrochloride 10 mg", packing: "10*10 Alu/Alu" },
      { id: 142, product: "Gabapentin I.P. 300 mg", packing: "10*10 Alu/Alu" },
      { id: 143, product: "Itraconazole 100mg", packing: "10*4 Alu/Alu" },
      { id: 144, product: "Itraconazole 100mg", packing: "10*10 Alu/Alu" },
      { id: 145, product: "Itraconazole 200 mg", packing: "10*10 Alu/Alu" },
      { id: 146, product: "Itraconazole 200mg", packing: "10*1*4 Blister" },
      { id: 147, product: "Levo Glutamide Containing Peptide 250mg + 2-Amino Ethane Sulphonic Acid 250mg + Glutamyl-Cysteinyl Glycine 50mg + Methylcobalamin 1500Mcg + Folic Acid 1.5mg, Pyridoxine 5mg + Thiamine 5mg + Riboflavin 5mg", packing: "3*10 Alu/Alu" },
      { id: 148, product: "L-Ornithine L-Aspartate 50mg + Silymarin 35mg + Pyridoxine Hcl 2mg + Folic Acid 176.47 mcg", packing: "10*10 Alu/Alu" },
      { id: 149, product: "L-Ornithine L-Aspartate 50mg + Pancreatin", packing: "10*10 Blister" },
      { id: 150, product: "Isotretinoin 20mg", packing: "10*1*10 Soft Gel" },
      { id: 151, product: "Isoxsuprine 40 mg", packing: "10*10 Alu/Alu" },
      { id: 152, product: "Ibuprofen Tablets I.P. 400mg", packing: "10*10 Blister" },
      { id: 153, product: "Ibuprofen Tablets I.P. 600mg", packing: "10*10 Blister" },
      { id: 154, product: "Ketorolac Tromethamine 10 Mg Dispersible Tablet", packing: "10*15 Alu/Alu" },
      { id: 155, product: "Progesterone 100 mg", packing: "10*10 Soft Gel" },
      { id: 156, product: "Progesterone Gel 8% w/w", packing: "15*1 Prefilled Applicator" },
      { id: 157, product: "Progesteron 200 mg Natural Micronised SR Tablet", packing: "10*10 Blister" },
      { id: 158, product: "medroxyprogesterone acetate 10mg", packing: "10*10 Alu/Alu" },
      { id: 159, product: "Progesteron 200 mg Natural Micronised Soft gel capsule", packing: "10*1*10 Soft Gel" },
      { id: 160, product: "Progesteron 300 mg Natural Micronised SR", packing: "10*1*10 Alu/Alu" },
      { id: 161, product: "Letrozole Tablet 2.5 mg", packing: "10X5 Blister" },
      { id: 162, product: "Lansoprazole 15 mg Junior Mouth dissolving Tablet", packing: "10*15 Alu/Alu" },
      { id: 163, product: "Lornoxicam 4 mg + Paracetamol 325 mg Tablet", packing: "10*10 Alu/Alu" },
      { id: 164, product: "Grape Seed Extract 25mg + Lycopene 2mg + Multivitamins + Multiminerals + Antioxidant", packing: "10*1*10 Soft-Gel" },
      { id: 165, product: "Lycopene + Mecobalamine + Selenium", packing: "5*10 Alu/Alu" },
      { id: 166, product: "Levetiracetam 500mg tablets", packing: "10X10 Blister" },
      { id: 167, product: "Tacrolimus Capsules IP 1 mg", packing: "10*1*10 Alu/Alu" },
      { id: 168, product: "Pregabalin 75 mg + Methylcobalamin 1500 Mcg + Nortriptyline Hydrochloride 10 mg", packing: "10*10 Alu/Alu" },
      { id: 169, product: "Pregabalin 75mg & Methylcobalamin 750Mcg Capsule", packing: "10*10 Alu/Alu" },
      { id: 170, product: "Nortriptyline 10mg + Pregabalin 75 mg", packing: "10*10 Alu/Alu" },
      { id: 171, product: "Pregabalin 300mg cap", packing: "10x10Alu/Alu" },
      { id: 172, product: "Mecobalamin 500Mcg + Gabapentin 300mg", packing: "10*10 Alu/Alu" },
      { id: 173, product: "Methylcobalamin 1500 Mcg + L Methylfolate 1mg & Pyridoxal + 0.5 Phosphate (In Drug Formulations)", packing: "10*10 Strip Pack" },
      { id: 174, product: "L-Carnitine L-Tartrate 500mg + Cynocobalamin 1.5Mcg + Folic acid 176.47 mcg", packing: "10*1*10 Alu/Alu" },
      { id: 175, product: "Mecobalamin 1500Mcg + Alpha Lipoic Acid 100mg + Pyridoxine 3mg + Folic Acid 1.5mg + Thiamine 10mg + Nutrients Capsule (In Drug Formulations)", packing: "10*10 Alu/Alu" },
      { id: 176, product: "Ivermectin 12 mg", packing: "10*10 Alu/Alu" },
      { id: 177, product: "Paracetamol 650mg Tablet", packing: "10*15 Blister" },
      { id: 178, product: "Paracetamol 1000 mg SR Tablet", packing: "10*1*12 Blister" },
      { id: 179, product: "Mefenamic Acid 500mg + Paracetamol 325mg Tablet", packing: "10*10 Blister" },
      { id: 180, product: "Montelukast 10mg + Fexofenadine 120mg", packing: "10*10 Alu/Alu" },
      { id: 181, product: "Amoxycillin 250mg + Clavulanate Acid 125mg", packing: "10*10 Alu/Alu" },
      { id: 182, product: "Amoxycilllin 500 + Clavulanate Acid 125mg + LB", packing: "10*1*10 Alu/Alu" },
      { id: 183, product: "Amoxycillin Trihydrate 250 mg + Cloxacillin 250mg + Lb 1.7 Billion Spores Capsules", packing: "10*10 Alu/Alu" },
      { id: 184, product: "Amoxycillin 250mg", packing: "20*10 Blister" },
      { id: 185, product: "Amoxycillin 500 mg", packing: "20*10 Blister" },
      { id: 186, product: "Norethisterone 5mg tab", packing: "10*10,ALU/ALU" },
      { id: 187, product: "Nimesulide 100 mg + Phenylphrine Hcl 10 mg + Cetrizine Dihydrochloride 5 mg + Caffeine 30 mg", packing: "20*10 Blister" },
      { id: 188, product: "Faropenum Sodium 200 mg", packing: "10*1*6 Strip Pack" },
      { id: 189, product: "Faropenum Sodium 300 mg", packing: "10*1*6 Alu/Alu" },
      { id: 190, product: "Ofloxacin 400mg Tablet", packing: "10*10 Alu/Alu" },
      { id: 191, product: "Carbonil Iron + Zinc Folic Acid + Vitamin B12", packing: "10*10 Blister" },
      { id: 192, product: "Collegen Peptide Type I 40 mg + Sodium Hyaluronatesulphate Glucosamine Sulphate 500 mg + Vitamin C + Vitamin A + Vitamin B2 + Vitamin Bi + Vitamin B6, Folic Acid 176.47 mcg & Zinc", packing: "10*1*10 Alu/Alu" },
      { id: 193, product: "Diacerin 50mg + Glucosamine Sulphate Potassium 446mg Chloride 750mg + Methylsulfonymethanr 250mg", packing: "10*10 Alu/Alu" },
      { id: 194, product: "Pregabalin 75 mg + Duloxetin 20 mg", packing: "10*10 Alu/Alu" },
      { id: 195, product: "Palmitoylethanolamide (Micronized Grade) 300 mg + Daidzein 50 mg + Genistein 4 mg + Energy Value 2.420Kcal + Proteins 0.073G + Total Fat 0.171 G + Cholesterol 0.000 mg + Trans Fat 0.000G + Saturated Fat 0.000G + Carbohydrates 0.149G + Added Suger 0.000G + Sodium 0.126 mg", packing: "10*1*10 Alu/Alu" },
      { id: 196, product: "Allylestrenol 5mg", packing: "10*10 Alu/Alu" },
      { id: 197, product: "Pancreatin capsules 300 mg(25000)", packing: "10*10 Strip Pack" },
      { id: 198, product: "Citicoline Sodium 500 mg + Piracetam 800 mg Tablet", packing: "10*10 Alu/Alu" },
      { id: 199, product: "Piracetam 400 mg Tablet", packing: "10*10 Alu/Alu" },
      { id: 200, product: "Methylprednisolone Tablets Ip 4mg", packing: "10*10 Medrol Die" },
      { id: 201, product: "Methylprednisolone Tablets Ip 8mg", packing: "10*14 Medrol Die" },
      { id: 202, product: "Methylprednisolone Tablets Ip 16mg", packing: "10*10Alu/Alu" },
      { id: 203, product: "Methylprednisolone Tablets Ip 16mg", packing: "10*14 Medrol Die" },
      { id: 204, product: "Cefpodoxime 100 mg Dispersible", packing: "10*10 Alu/Alu" },
    ]
   },
    {
    "category": "CARDIO & DIABETIC TABLETS",
    "products": [
      {"id": 1, "product": "Amlodipine + Atenolol", "strength": "5mg + 50mg", "packing": "10*10 Alu/Alu"},
      {"id": 2, "product": "Amlodipine", "strength": "5mg", "packing": "10*10 Blister"},
      {"id": 3, "product": "Amlodipine", "strength": "10mg", "packing": "10*10 Blister"},
      {"id": 4, "product": "Bisoprolol Fumarate", "strength": "2.5mg", "packing": "10*10 Blister"},
      {"id": 5, "product": "Bisoprolol Fumarate", "strength": "5mg", "packing": "10*10 Blister"},
      {"id": 6, "product": "Cilnidipine", "strength": "10mg", "packing": "10*10 Alu/Alu"},
      {"id": 7, "product": "Cilnidipine", "strength": "20mg", "packing": "10*10 Alu/Alu"},
      {"id": 8, "product": "Carvedilol", "strength": "6.25mg", "packing": "10*10 Blister"},
      {"id": 9, "product": "Carvedilol", "strength": "12.5mg", "packing": "10*10 Blister"},
      {"id": 10, "product": "Carvedilol", "strength": "3.125mg", "packing": "10*10 Blister"},
      {"id": 11, "product": "Eplerenone", "strength": "25mg", "packing": "10*10 Blister"},
      {"id": 12, "product": "Metformin HCL", "strength": "500mg", "packing": "20*10 Blister"},
      {"id": 13, "product": "Dapagliflozin", "strength": "10mg", "packing": "10*14 Alu/Alu"},
      {"id": 14, "product": "Dapagliflozin + Metformin", "strength": "10mg + 500mg", "packing": "10*10 Alu/Alu"},
      {"id": 15, "product": "Dapagliflozin + Vildagliptin", "strength": "10mg + 100mg", "packing": "10*10 Alu/Alu"},
      {"id": 16, "product": "Vildagliptin", "strength": "50mg", "packing": "10*15 Alu/Alu"},
      {"id": 17, "product": "Vildagliptin + Metformin", "strength": "50mg + 500mg", "packing": "10*15 Alu/Alu"},
      {"id": 18, "product": "Ramipril + Metoprolol", "strength": "2.5mg + 23.75mg", "packing": "10*10 Blister"},
      {"id": 19, "product": "Gliclazide + Metformin", "strength": "80mg + 500mg", "packing": "10*15 Blister"},
      {"id": 20, "product": "Glimepiride + Metformin", "strength": "1mg + 500mg", "packing": "10*10 Blister"},
      {"id": 21, "product": "Glimepiride + Metformin", "strength": "2mg + 500mg", "packing": "10*10 Blister"},
      {"id": 22, "product": "Glimepiride + Metformin", "strength": "2mg + 1000mg", "packing": "10*15 Blister"},
      {"id": 23, "product": "Glimepiride + Metformin + Pioglitazone", "strength": "1mg + 500mg + 15mg", "packing": "10*10 Blister"},
      {"id": 24, "product": "Glimepiride + Pioglitazone + Metformin", "strength": "2mg + 15mg + 500mg (ER)", "packing": "10*10 Blister"},
      {"id": 25, "product": "Metformin (SR) + Glimepiride + Voglibose", "strength": "500mg + 2mg + 0.2mg", "packing": "10*10 Blister"},
      {"id": 26, "product": "Linagliptin", "strength": "5mg", "packing": "10*10 Blister"},
      {"id": 27, "product": "Linagliptin + Dapagliflozin", "strength": "5mg + 10mg", "packing": "10*10 Alu/Alu"},
      {"id": 28, "product": "Linagliptin + Metformin", "strength": "2.5mg + 500mg", "packing": "10*10 Blister"},
      {"id": 29, "product": "Losartan Potassium", "strength": "50mg", "packing": "10*10 Blister"},
      {"id": 30, "product": "Losartan Potassium", "strength": "50mg", "packing": "10*10 Blister"},
      {"id": 31, "product": "Metoprolol", "strength": "25mg", "packing": "10*10 Alu/Alu"},
      {"id": 32, "product": "Metoprolol", "strength": "50mg", "packing": "10*10 Alu/Alu"},
      {"id": 33, "product": "Metoprolol + Telmisartan", "strength": "25mg + 40mg", "packing": "10*10 Alu/Alu"},
      {"id": 34, "product": "Metoprolol + Telmisartan", "strength": "50mg + 40mg", "packing": "10*10 Alu/Alu"},
      {"id": 35, "product": "Nitroglycerine", "strength": "2.6mg", "packing": "30 Tablets"},
      {"id": 36, "product": "Nitroglycerine", "strength": "6.4mg", "packing": "30 Tablets"},
      {"id": 37, "product": "Prasugrel", "strength": "10mg", "packing": "10*10 Alu/Alu"},
      {"id": 38, "product": "Rosuvastatin", "strength": "10mg", "packing": "10*10 Alu/Alu"},
      {"id": 39, "product": "Rosuvastatin", "strength": "20mg", "packing": "10*10 Alu/Alu"},
      {"id": 40, "product": "Rosuvastatin", "strength": "40mg", "packing": "10*10 Alu/Alu"},
      {"id": 41, "product": "Rosuvastatin + Fenofibrate", "strength": "10mg + 160mg", "packing": "10*10 Alu/Alu"},
      {"id": 42, "product": "Rosuvastatin + Aspirin + Clopidogrel", "strength": "10mg + 75mg + 75mg", "packing": "10*10 Alu/Alu"},
      {"id": 43, "product": "Rosuvastatin + Aspirin + Clopidogrel", "strength": "20mg + 75mg + 75mg", "packing": "10*10 Alu/Alu"},
      {"id": 44, "product": "Rosuvastatin + Clopidogrel", "strength": "20mg + 75mg", "packing": "10*10 Alu/Alu"},
      {"id": 45, "product": "Rosuvastatin + Aspirin", "strength": "10mg + 75mg", "packing": "10*10 Strip Pack"},
      {"id": 46, "product": "Sitagliptin + Metformin", "strength": "50mg + 500mg", "packing": "10*15 Blister"},
      {"id": 47, "product": "Sitagliptin + Dapagliflozin + Metformin", "strength": "100mg + 10mg + 1000mg", "packing": "10*10 Alu/Alu"},
      {"id": 48, "product": "Ticagrelor", "strength": "90mg", "packing": "10x14 Blister"},
      {"id": 49, "product": "Telmisartan + Chlorthalidone", "strength": "40mg + 12.50mg", "packing": "10x15 Alu/Alu"},
      {"id": 50, "product": "Telmisartan + Cilnidipine", "strength": "40mg + 10mg", "packing": "10x15 Alu/Alu"},
      {"id": 51, "product": "Telmisartan + Chlorthalidone + Cilnidipine", "strength": "40mg + 12.5mg + 10mg", "packing": "10*10 Alu/Alu"},
      {"id": 52, "product": "Telmisartan + Metoprolol + Cilnidipine", "strength": "40mg + 50mg + 10mg", "packing": "10x15 Alu/Alu"},
      {"id": 53, "product": "Telmisartan + Amlodipine + Hydrochlorothiazide", "strength": "40mg + 5mg + 12.5mg", "packing": "10x15 Alu/Alu"},
      {"id": 54, "product": "Telmisartan", "strength": "40mg", "packing": "10*15 Alu/Alu"},
      {"id": 55, "product": "Amlodipine + Telmisartan", "strength": "5mg + 40mg", "packing": "10*15 Alu/Alu"},
      {"id": 56, "product": "Telmisartan + Hydrochlorothiazide", "strength": "40mg + 12.5mg", "packing": "10*15 Alu/Alu"},
      {"id": 57, "product": "Spironolactone + Torsemide", "strength": "50mg + 10mg", "packing": "10*10 Blister"},
      {"id": 58, "product": "Spironolactone + Torsemide", "strength": "50mg + 20mg", "packing": "10*10 Blister"},
      {"id": 59, "product": "Thyroxine Sodium", "strength": "25mcg", "packing": "100 Tab Pet Bottle"},
      {"id": 60, "product": "Thyroxine Sodium", "strength": "50mcg", "packing": "100 Tab Pet Bottle"},
      {"id": 61, "product": "Thyroxine Sodium", "strength": "75mcg", "packing": "100 Tab Pet Bottle"},
      {"id": 62, "product": "Thyroxine Sodium", "strength": "100mcg", "packing": "100 Tab Pet Bottle"},
      {"id": 63, "product": "Trimetazidine Hydrochloride", "strength": "35mg", "packing": "10*10 Alu/Alu"},
      {"id": 64, "product": "Sacubitril + Valsartan", "strength": "24mg + 26mg", "packing": "10*14 Alu/Alu"},
      {"id": 65, "product": "Sacubitril + Valsartan", "strength": "49mg + 51mg", "packing": "10*14 Alu/Alu"},
      {"id": 66, "product": "Ramipril", "strength": "5mg", "packing": "10*10 Blister"},
      {"id": 67, "product": "Ramipril", "strength": "2.5mg", "packing": "10*10 Blister"},
      {"id": 68, "product": "Atorvastatin + Aspirin", "strength": "10mg + 75mg", "packing": "10*10 Strip Pack"},
      {"id": 69, "product": "Atorvastatin + Clopidogrel + Aspirin", "strength": "20mg + 75mg + 75mg", "packing": "10*10 Strip Pack"},
      {"id": 70, "product": "Atorvastatin", "strength": "40mg", "packing": "10*10 Alu/Alu"},
      {"id": 71, "product": "Atorvastatin", "strength": "20mg", "packing": "10*10 Alu/Alu"},
      {"id": 72, "product": "Atorvastatin", "strength": "10mg", "packing": "10*10 Alu/Alu"}
    ]
  },
  {
    "category": "SYRUP & SUSPENSION",
    "products": [
      {"id": 1, "product": "Disodium Hydrogen Citrate", "strength": "1.25mg", "packing": "100ml Pet Bottle"},
      {"id": 2, "product": "Azithromycin", "strength": "100mg", "packing": "30ml Pet Bottle"},
      {"id": 3, "product": "Azithromycin", "strength": "200mg", "packing": "30ml Pet Bottle"},
      {"id": 4, "product": "Bilastine + Montelukast", "strength": "10mg + 4mg", "packing": "60ml Pet Bottle"},
      {"id": 5, "product": "Calcium Carbonate + Magnesium Hydroxide + Zinc Gluconate + Vitamin D3", "strength": "625mg + 180mg + 14mg + 200IU", "packing": "200ml Pet Bottle"},
      {"id": 6, "product": "Ambroxol + Terbutaline + Guaiphenesin + Menthol", "strength": "15mg + 1.25mg + 50mg + 2.5mg", "packing": "60ml Pet Bottle"},
      {"id": 7, "product": "Dextromethorphan + Ambroxol + Chlorpheniramine + Phenylephrine", "strength": "10mg + 15mg + 2mg + 5mg", "packing": "100ml Pet Bottle"},
      {"id": 8, "product": "Ambroxol + Terbutaline + Guaiphenesin + Menthol", "strength": "15mg + 1.25mg + 50mg + 2.5mg", "packing": "60ml Pet Bottle"},
      {"id": 9, "product": "Ayurvedic Cough Syrup", "strength": "With Honey", "packing": "100ml Pet Bottle"},
      {"id": 10, "product": "Ambroxol + Terbutaline + Guaiphenesin + Menthol", "strength": "15mg + 1.25mg + 50mg + 2.5mg", "packing": "100ml Pet Bottle"},
      {"id": 11, "product": "Terbutaline + Bromhexine + Guaiphenesin + Menthol", "strength": "1.25mg + 4mg + 50mg + 0.5mg", "packing": "100ml Pet Bottle"},
      {"id": 12, "product": "Terbutaline + Bromhexine + Guaiphenesin + Menthol", "strength": "1.25mg + 4mg + 50mg + 0.5mg", "packing": "60ml Pet Bottle"},
      {"id": 13, "product": "Dextromethorphan + Chlorpheniramine + Phenylephrine", "strength": "10mg + 2mg + 5mg", "packing": "60ml Pet Bottle"},
      {"id": 14, "product": "Dextromethorphan + Chlorpheniramine + Phenylephrine", "strength": "10mg + 2mg + 5mg", "packing": "100ml Pet Bottle"},
      {"id": 15, "product": "Levosalbutamol + Ambroxol + Guaiphenesin", "strength": "1mg + 30mg + 50mg", "packing": "100ml Pet Bottle"},
      {"id": 16, "product": "Levosalbutamol + Ambroxol + Guaiphenesin", "strength": "0.5mg + 15mg + 50mg", "packing": "60ml Pet Bottle"},
      {"id": 17, "product": "Acebrophylline + Guaiphenesin + Terbutaline", "strength": "50mg + 50mg + 1.25mg", "packing": "100ml Pet Bottle"},
      {"id": 18, "product": "Cyproheptadine + Tricholine Citrate + Sorbitol", "strength": "2mg + 275mg + Sorbitol", "packing": "200ml Pet Bottle"},
      {"id": 19, "product": "Cyproheptadine + Vitamin B Complex", "strength": "2mg + B1 2.5mg + B2 2.5mg + B6 0.75mg + D-Panthenol 2.5mg + Niacinamide 22.5mg", "packing": "200ml Pet Bottle"},
      {"id": 20, "product": "Clarithromycin", "strength": "Oral Suspension", "packing": "15gm/30ml"},
      {"id": 21, "product": "Vitamin D3", "strength": "60000 IU", "packing": "5ml Glass Bottle"},
      {"id": 22, "product": "Sodium Alginate + Sodium Bicarbonate + Calcium Carbonate", "strength": "250mg + 133.5mg + 80mg", "packing": "200ml Pet Bottle"},
      {"id": 23, "product": "Ferrous Ascorbate + Folic Acid + Cyanocobalamin + Lysine", "strength": "30mg + 1000mcg + 5mcg + 35mg", "packing": "200ml Pet Bottle"},
      {"id": 24, "product": "Lactulose", "strength": "10gm", "packing": "100ml Pet Bottle"},
      {"id": 25, "product": "Lactulose", "strength": "10gm", "packing": "200ml Pet Bottle"},
      {"id": 26, "product": "Instant Energy Drink with Vitamin C", "strength": "", "packing": "200ml Pet Bottle"},
      {"id": 27, "product": "Omega-3 + EPA + DHA", "strength": "", "packing": "225ml Pet Bottle"},
      {"id": 28, "product": "Protein + Multivitamin + L-Lysine", "strength": "", "packing": "200ml Pet Bottle"},
      {"id": 29, "product": "Chlorhexidine Gluconate", "strength": "0.20% W/V", "packing": "100ml Special Pet Bottle"},
      {"id": 30, "product": "Ibuprofen + Paracetamol", "strength": "100mg + 162.5mg", "packing": "100ml Pet Bottle"},
      {"id": 31, "product": "Magaldrate + Simethicone", "strength": "400mg + 20mg", "packing": "170ml Pet Bottle"},
      {"id": 32, "product": "Magaldrate + Simethicone + Oxetacaine", "strength": "", "packing": "200ml Pet Bottle"},
      {"id": 33, "product": "Sucralfate + Oxetacaine", "strength": "1gm + 20mg", "packing": "200ml Pet Bottle"},
      {"id": 34, "product": "Sucralfate + Oxetacaine", "strength": "1gm + 20mg", "packing": "100ml Pet Bottle"},
      {"id": 35, "product": "Silymarin + Vitamin B Complex", "strength": "35mg + B1 1.5mg + B2 1.5mg + B6 1.5mg + B12 1mg + Niacinamide 18mg + D-Panthenol 5mg", "packing": "200ml Pet Bottle"},
      {"id": 36, "product": "Lycopene + Multivitamin + Multimineral", "strength": "2000mcg + Niacinamide 25mg + Folic Acid 100mcg + Selenium 35mcg + Zinc 3mg + Iodine 100mcg + Copper 500mcg + Vitamin B12 1mcg + Vitamin B6 1.5mg", "packing": "200ml Pet Bottle"},
      {"id": 37, "product": "Lycopene + Multivitamin + Multimineral", "strength": "2000mcg + Niacinamide 25mg + Folic Acid 100mcg + Selenium 35mcg + Zinc 3mg + Iodine 100mcg + Copper 500mcg + Vitamin B12 1mcg + Vitamin B6 1.5mg", "packing": "100ml Pet Bottle"},
      {"id": 38, "product": "Lycopene + Cyanocobalamin + Multivitamin + Multimineral", "strength": "", "packing": "200ml Pet Bottle"},
      {"id": 39, "product": "Liquid Paraffin + Milk of Magnesia + Sodium Picosulphate", "strength": "1.25ml + 3.75ml + 3.33mg", "packing": "170ml Pet Bottle"},
      {"id": 40, "product": "Papaya + Madhukparni + Aloe Vera + Amla + Haritiki + Giloy + Danamethi + Punarnava + Tulsi + Trikatu", "strength": "1200mg + 400mg + 200mg + 200mg + 100mg + 100mg + 100mg + 100mg + 100mg + 100mg", "packing": "200ml Pet Bottle"},
      {"id": 41, "product": "Potassium Citrate + Magnesium Citrate + Pyridoxine", "strength": "1100mg + 375mg + 20mg", "packing": "200ml Pet Bottle"},
      {"id": 42, "product": "Potassium Citrate + Magnesium Citrate + Pyridoxine", "strength": "", "packing": "200ml Pet Bottle"},
      {"id": 43, "product": "Lycopene + Ginkgo Biloba + Ginseng", "strength": "", "packing": "200ml Pet Bottle"},
      {"id": 44, "product": "L-Lysine + Multivitamin + Multimineral", "strength": "", "packing": "200ml Pet Bottle"},
      {"id": 45, "product": "Fungal Diastase + Papain + B Complex", "strength": "50mg + 10mg + B Complex", "packing": "200ml Pet Bottle"},
      {"id": 46, "product": "Fungal Diastase + Papain + B Complex", "strength": "50mg + 10mg + B Complex", "packing": "100ml Pet Bottle"}
    ]
  },
  {
    "category": "INJECTIONS",
    "products": [
      {"id": 1, "product": "Alfabeta Arteether", "strength": "150mg", "packing": "3*2ml Amp"},
      {"id": 2, "product": "Amikacin", "strength": "500mg", "packing": "2ml Single Vial"},
      {"id": 3, "product": "Amikacin", "strength": "250mg", "packing": "3ml Single Vial"},
      {"id": 4, "product": "Amikacin", "strength": "100mg", "packing": "4ml Single Vial"},
      {"id": 5, "product": "Nutritive Infusion", "strength": "5.459% w/v", "packing": "100ml Vial"},
      {"id": 6, "product": "Medroxyprogesterone", "strength": "150mg/ml", "packing": "1ml Single Vial"},
      {"id": 7, "product": "Enoxaparin", "strength": "60mg", "packing": "Prefilled Syringe"},
      {"id": 8, "product": "Enoxaparin", "strength": "40mg", "packing": "Prefilled Syringe"},
      {"id": 9, "product": "Acetylcysteine", "strength": "200mg", "packing": "5*2ml Tray Pack"},
      {"id": 10, "product": "Dobutamine", "strength": "50mg", "packing": "5*5ml Tray Pack"},
      {"id": 11, "product": "Acyclovir", "strength": "250mg", "packing": "Vial with WFI"},
      {"id": 12, "product": "Acyclovir", "strength": "500mg", "packing": "Vial with WFI"},
      {"id": 13, "product": "Ceftriaxone + Tazobactam", "strength": "1gm + 125mg", "packing": "Vial with WFI"},
      {"id": 14, "product": "Ceftriaxone + Tazobactam", "strength": "250mg + 62.5mg", "packing": "Vial with WFI"},
      {"id": 15, "product": "Ceftriaxone", "strength": "500mg", "packing": "Single Vial with WFI"},
      {"id": 16, "product": "Ceftriaxone", "strength": "1000mg", "packing": "Single Vial with WFI"},
      {"id": 17, "product": "Ceftriaxone + Sulbactam", "strength": "250mg + 125mg", "packing": "Single Vial with WFI"},
      {"id": 18, "product": "Ceftriaxone + Sulbactam", "strength": "1000mg + 500mg", "packing": "Single Vial with WFI"},
      {"id": 19, "product": "Citicoline", "strength": "500mg", "packing": "2ml Ampoule"},
      {"id": 20, "product": "Cefuroxime", "strength": "750mg", "packing": "Single Vial with WFI"},
      {"id": 21, "product": "Clindamycin", "strength": "300mg", "packing": "2ml Ampoule"},
      {"id": 22, "product": "Clindamycin", "strength": "600mg", "packing": "4ml Ampoule"},
      {"id": 23, "product": "Cefoperazone + Sulbactam", "strength": "1000mg + 500mg", "packing": "Single Vial with WFI"},
      {"id": 24, "product": "Cefoperazone + Sulbactam", "strength": "500mg + 500mg", "packing": "Single Vial with WFI"},
      {"id": 25, "product": "Clarithromycin", "strength": "500mg", "packing": "Vial with WFI"},
      {"id": 26, "product": "Levocarnitine", "strength": "1gm", "packing": "5*5ml Tray Pack"},
      {"id": 27, "product": "Cerebroprotein Hydrolysate", "strength": "60mg", "packing": "Single Vial Tray Pack"},
      {"id": 28, "product": "Colistimethate Sodium", "strength": "1MIU", "packing": "Single Vial Tray Pack"},
      {"id": 29, "product": "Dicyclomine + Diclofenac", "strength": "Hydrochloride & Sodium", "packing": "10*2ml Tray Pack"},
      {"id": 30, "product": "Nandrolone Decanoate", "strength": "25mg", "packing": "Dispo Pack"},
      {"id": 31, "product": "Nandrolone Decanoate", "strength": "50mg", "packing": "Dispo Pack"},
      {"id": 32, "product": "Cholecalciferol", "strength": "60000 IU", "packing": "5*1ml Tray Pack"},
      {"id": 33, "product": "Diclofenac Sodium + Benzyl Alcohol", "strength": "75mg + 4% W/V", "packing": "10*1ml Tray Pack"},
      {"id": 34, "product": "Doxycycline", "strength": "100mg", "packing": "10ml + Vit C + WFI Tray Pack"},
      {"id": 35, "product": "Drotaverine Hydrochloride + Benzyl Alcohol", "strength": "20mg + 4% V/V", "packing": "10*2 Amp Tray Pack"},
      {"id": 36, "product": "Ferric Carboxymaltose", "strength": "500mg", "packing": "10ml Single"},
      {"id": 37, "product": "Pantoprazole", "strength": "40mg", "packing": "Single Vial with WFI"},
      {"id": 38, "product": "Hydrocortisone Sodium Succinate", "strength": "100mg", "packing": "Vial with WFI"},
      {"id": 39, "product": "Esomeprazole", "strength": "40mg", "packing": "Vial with WFI"},
      {"id": 40, "product": "Methylprednisolone Acetate", "strength": "40mg", "packing": "1ml Single Vial"},
      {"id": 41, "product": "Methylprednisolone Acetate", "strength": "80mg", "packing": "2ml Vial"},
      {"id": 42, "product": "Iron Sucrose", "strength": "100mg", "packing": "5ml Amp Tray Pack"},
      {"id": 43, "product": "Human Chorionic Gonadotropin", "strength": "5000 IU", "packing": "Vial + Amp + Tray"},
      {"id": 44, "product": "Hydroxyprogesterone", "strength": "500mg", "packing": "2ml Dispo Pack"},
      {"id": 45, "product": "Glutathione", "strength": "600mg", "packing": "Single Vial Tray"},
      {"id": 46, "product": "L-Ornithine + L-Aspartate", "strength": "5mg", "packing": "1*10ml Infusion"},
      {"id": 47, "product": "Paracetamol", "strength": "1000mg", "packing": "100ml Infusion"},
      {"id": 48, "product": "Heparin Sodium", "strength": "5000 IU + Benzyl Alcohol 1.0%", "packing": "5ml"},
      {"id": 49, "product": "Heparin Sodium", "strength": "25000 IU + Benzyl Alcohol 1.0%", "packing": "5ml"},
      {"id": 50, "product": "Levetiracetam", "strength": "500mg", "packing": "Vial with WFI"},
      {"id": 51, "product": "Labetalol", "strength": "20mg", "packing": "2*4ml Tray Pack"},
      {"id": 52, "product": "Mecobalamin + Benzyl Alcohol", "strength": "1500mcg + 1.5% V/V", "packing": "5*2ml Tray Pack"},
      {"id": 53, "product": "Methylcobalamin + Benzyl Alcohol", "strength": "2500mcg + 2.0%", "packing": "Dispo Pack"},
      {"id": 54, "product": "Mecobalamin + Nicotinamide + Pyridoxine + Benzyl Alcohol", "strength": "1000mcg + 100mg + 100mg + 2% V/V", "packing": "Dispo Pack"},
      {"id": 55, "product": "Menotropin", "strength": "75 IU", "packing": "Vial + Amp"},
      {"id": 56, "product": "Meropenem", "strength": "1000mg", "packing": "Vial with WFI"},
      {"id": 57, "product": "Meropenem + Sulbactam", "strength": "1.5gm", "packing": "Vial with WFI"},
      {"id": 58, "product": "Netilmicin", "strength": "50mg", "packing": "Single Vial"},
      {"id": 59, "product": "Amoxycillin + Clavulanate", "strength": "1000mg + 200mg", "packing": "Vial with WFI"},
      {"id": 60, "product": "Ofloxacin", "strength": "0.2% W/V", "packing": "100ml Infusion"},
      {"id": 61, "product": "Piperacillin + Tazobactam", "strength": "4000mg + 500mg", "packing": "Vial with WFI"},
      {"id": 62, "product": "Piperacillin + Tazobactam", "strength": "2gm + 0.25mg", "packing": "Vial with WFI"},
      {"id": 63, "product": "Methylprednisolone Succinate", "strength": "1gm", "packing": "Vial with WFI"},
      {"id": 64, "product": "Methylprednisolone Succinate", "strength": "500mg", "packing": "Vial with WFI"},
      {"id": 65, "product": "Methylprednisolone Sodium Succinate", "strength": "40mg", "packing": "Vial with WFI"},
      {"id": 66, "product": "Methylprednisolone Sodium Succinate", "strength": "125mg", "packing": "Vial with WFI"},
    ]
    },
       {
      "category": "PEDIATRIC DROPS/SUSPENSIONS/DRY SYRUPS",
      "products": [
        { "id": 1, "product": "Aceclofenac + Paracetamol Suspension", "strength": "50mg+125mg/60ml", "packing": "Monocarton Pet Bottle" },
        { "id": 2, "product": "Albendazole + Ivermectin Syrup", "strength": "400mg+6mg/10ml", "packing": "Monocarton Pet Bottle" },
        { "id": 3, "product": "Albendazole Oral Suspension", "strength": "200mg/10ml", "packing": "Monocarton Pet Bottle" },
        { "id": 4, "product": "Phenylephrine HCI & Chlorpheniramine Maleate Drops", "strength": "15ml", "packing": "Pet Bottle" },
        { "id": 5, "product": "Cyproheptadine Hydrochloride + Tricholine Citrate Syrup", "strength": "2mg+275mg/30ml", "packing": "Pet Bottle" },
        { "id": 6, "product": "Cefixime Drops", "strength": "25mg/10ml", "packing": "Pet Bottle with dropper" },
        { "id": 7, "product": "Cefixime + Lactic Acid Bacillus Dry Syrup", "strength": "50mg+60M spores/30ml", "packing": "Dry Syp Pet Bottle" },
        { "id": 8, "product": "Cefixime Dry Syrup", "strength": "50mg/30ml", "packing": "Dry Syp Pet Bottle" },
        { "id": 9, "product": "Cefixime + Potassium Clavulanate Dry Syrup", "strength": "50mg+28.5mg/30ml", "packing": "Dry Syrup With Water Pet Bottle" },
        { "id": 10, "product": "Cefixime + Ofloxacin Dry Syrup", "strength": "50mg+50mg/30ml", "packing": "Dry Syrup With Water Pet Bottle" },
        { "id": 11, "product": "Levocetirizine + Montelukast Syrup", "strength": "2.5mg+4mg/60ml", "packing": "Pet Bottle" },
        { "id": 12, "product": "Magnesium Hydoxide+Simethicone+Sodium Carboxymethylcellulose+Dried Aluminium Hydroxide Suspension", "strength": "185mg+50mg+100mg+830mg/170ml", "packing": "Pet Bottle" },
        { "id": 13, "product": "PCM+Phenylephrine+Chlorpheniramine+Sodium Citrate+Ammonium Cl+Menthol Suspension", "strength": "250mg+5mg+2mg+60mg+120mg+1mg/60ml", "packing": "Monocarton Pet Bottle" },
        { "id": 14, "product": "Paracetamol+Phenylephrine+CPM+Sodium Citrate Suspension", "strength": "125mg+5mg+1mg+60mg/60ml", "packing": "Monocarton Pet Bottle" },
        { "id": 15, "product": "Deflazacort Suspension", "strength": "6mg/30ml", "packing": "Pet Bottle" },
        { "id": 16, "product": "Levosalbutamol+Ambroxol+Guaiphensin Drops", "strength": "0.25mg+7.5mg+12.5mg/15ml", "packing": "Pet Bottle with Dropper" },
        { "id": 17, "product": "Vitamin D3 Syrup", "strength": "400IU (10mcg)/30ml", "packing": "Dropper" },
        { "id": 18, "product": "Multivitamin+Multimineral+Antioxidant Syrup", "strength": "30ml", "packing": "Drops With Dropper" },
        { "id": 19, "product": "Domperidone Drops", "strength": "10mg/30ml", "packing": "Pet Bottle with dropper" },
        { "id": 20, "product": "Fexofenadine Hydrochloride Oral Suspension", "strength": "60ml", "packing": "Pet Bottle" },
        { "id": 21, "product": "Cefuroxime Dry Syrup", "strength": "125mg/30ml", "packing": "Pet Bottle" },
        { "id": 22, "product": "Bacillus Clausii Spores Suspension", "strength": "2B spores/10*5ml", "packing": "Pet Bottle" },
        { "id": 23, "product": "Simethicone+Dill Oil+Fennel Oil Drop", "strength": "40mg+0.005ml+0.0007ml/30ml", "packing": "Pet Bottle" },
        { "id": 24, "product": "Zinc Gluconate", "strength": "20mg/100ml", "packing": "Pet Bottle" },
        { "id": 25, "product": "Levofloxacin + Ornidazole Suspension", "strength": "125mg+125mg/60ml", "packing": "Pet Bottle with monocartoon" },
        { "id": 26, "product": "Paracetamol Suspension", "strength": "250mg/60ml", "packing": "Pet Bottle with monocartoon" },
        { "id": 27, "product": "Mefenamic Acid + Paracetamol Suspension", "strength": "50mg+125mg/60ml", "packing": "Pet Bottle with monocartoon" },
        { "id": 28, "product": "Mefenamic Acid + Paracetamol Suspension", "strength": "100mg+250mg/60ml", "packing": "Pet Bottle with monocartoon" },
        { "id": 29, "product": "Montelukast + Fexofenadine Hydrochloride Suspension", "strength": "4mg+30mg/60ml", "packing": "Pet Bottle with monocartoon" },
        { "id": 30, "product": "Amoxycillin + Potassium Clavulanate Dry Syrup", "strength": "28.5mg/30ml", "packing": "Pet Bottle" },
        { "id": 31, "product": "Amoxycillin + Potassium Clavulanate Oral", "strength": "400mg+57mg/30ml", "packing": "Pet Bottle" },
        { "id": 32, "product": "Amoxycillin + Clave Drops", "strength": "80mg+11.4mg/10ml", "packing": "Pet Bottle" },
        { "id": 33, "product": "Ofloxacin + Ornidazole + Racecadotril Suspension", "strength": "50mg+125mg+15mg/60ml", "packing": "Pet Bottle with monocartoon" },
        { "id": 34, "product": "Ofloxacin + Metronidazole Benzoate + Simethicone Suspension", "strength": "50mg+125mg/60ml", "packing": "Pet Bottle with monocartoon" },
        { "id": 35, "product": "Ofloxacin Suspension", "strength": "50mg/60ml", "packing": "Pet Bottle with monocartoon" },
        { "id": 36, "product": "Cefpodoxime Dry Syrup", "strength": "50mg/5ml/30ml", "packing": "Dry Syrup With Water Pet Bottle" },
        { "id": 37, "product": "Cefpodoxime Drops", "strength": "25mg/10ml", "packing": "Pet Bottle" },
        { "id": 38, "product": "Cefpodoxime Dry Syrup", "strength": "100mg/5ml/30ml", "packing": "Dry Syrup With Water Pet Bottle" },
        { "id": 39, "product": "Cefpodoxime + Potassium Clavulanate Dry Syrup", "strength": "100mg+62.5mg/30ml", "packing": "Pet Bottle" },
        { "id": 40, "product": "Cefpodoxime Proxetil + Potassium Clavulanate Dry Syrup", "strength": "50mg+31.25mg/30ml", "packing": "Suspension With Water Pet Bottle" },
        { "id": 41, "product": "Rifaximin Oral Suspension", "strength": "100mg/60ml", "packing": "Pet Bottle with monocartoon" },
        { "id": 42, "product": "Ranitidine Hydrochloride Oral Solution", "strength": "150mg/100ml", "packing": "Pet Bottle" },
        { "id": 43, "product": "Ondensetron Solution", "strength": "2mg/30ml", "packing": "With Monocarton Pet Bottle" },
        { "id": 44, "product": "Fungal Diastase + Papsin Suspension", "strength": "33.33mg+5mg/30ml", "packing": "Pet Bottle" }
      ]
    },
    {
      "category": "EYE & EAR DROPS",
      "products": [
        { "id": 1, "product": "Benzocaine+Chlorbutol+Turpentineoil+Para,Dichlorobenzene", "strength": "2.7%+5.0%+15.0%+2.0%/10ml", "packing": "Pet Bottle" },
        { "id": 2, "product": "Sodium Hyaluronate + Sodium Perborate", "strength": "0.1%+0.028%/10ml", "packing": "Pet Bottle" },
        { "id": 3, "product": "Moxifloxacin Eye Drops", "strength": "0.5%/5ml", "packing": "Pet Bottle" },
        { "id": 4, "product": "Moxifloxacin Hcl + Dexamethasone", "strength": "0.5%+0.1%/5ml", "packing": "Pet Bottle" },
        { "id": 5, "product": "Moxifloxacin + Ketorolac Tromethamine", "strength": "0.5%+0.5%/5ml", "packing": "Pet Bottle" },
        { "id": 6, "product": "Moxifloxacin + Tobramycin", "strength": "0.5%+0.3%/5ml", "packing": "Pet Bottle" },
        { "id": 7, "product": "Naphazoline Hcl + Chlorpheniramine Maleate + Methyl Cellulose + Phenyl Mercuric Nitrate", "strength": "0.1%+0.01%+0.25%+0.001%/10ml", "packing": "Pet Bottle" },
        { "id": 8, "product": "Ofloxacin + Dexamethasone", "strength": "3mg+0.1%/10ml", "packing": "Pet Bottle" },
        { "id": 9, "product": "Ciprofloxacin + Dexamethasone + Benzalkonium Chloride", "strength": "0.3%+0.1%+0.02%/10ml", "packing": "Pet Bottle" },
        { "id": 10, "product": "Olopatadine Hydrochloride Eye Drops", "strength": "0.1%/5ml", "packing": "Pet Bottle" },
        { "id": 11, "product": "Sodium Carboxymethyl-Cellulose + Stablized oxychloro Complex", "strength": "0.5%+0.0075%/10ml", "packing": "Pet Bottle" }
      ]
    },
    {
      "category": "NASAL DROPS",
      "products": [
        { "id": 1, "product": "Xylometazoline Hcl + Benzalkonium Chloride", "strength": "0.1%+0.012%/10ml", "packing": "Nasal Drops Pet Bottle" },
        { "id": 2, "product": "Xylometazoline Hcl + Benzalkonium Chloride", "strength": "0.05%+0.012%/10ml", "packing": "Pet Bottle" },
        { "id": 3, "product": "Azelastine Hydrochloride + Fluticasone Propionate", "strength": "140mcg+50mcg", "packing": "70 metered dose pump of 10 ml" },
        { "id": 4, "product": "Mometasone Aqueous Nasal Spray", "strength": "50mcg", "packing": "Metered dose pump of 10ml" },
        { "id": 5, "product": "Fluticasone Furoate Nasal Spray", "strength": "27.5mcg", "packing": "120 Metred Doses Special Pump" },
        { "id": 6, "product": "Sodium Chloride + Benzalkonium Chloride", "strength": "0.65%+0.01%/15ml", "packing": "Nasal Solution Special Bottle" }
      ]
    },
    {
      "category": "GEL/SOAPS/CREAM/LOTION",
      "products": [
        { "id": 1, "product": "Aloe Vera + Vitamin E Acetate Soap", "strength": "4%+0.5%", "packing": "75Gm Single" },
        { "id": 2, "product": "Hydrous Benzoyl Peroxide Soap", "strength": "5%", "packing": "75Gm Single" },
        { "id": 3, "product": "Hydroquinone + Tretinoin + Mometasone Furoate Cream", "strength": "0.2%+0.025%+0.1%", "packing": "15Gm Lemi Tube" },
        { "id": 4, "product": "Beclomethasone Dipropionate + Clotrimazole + Neomycin Sulphate Cream", "strength": "0.025%+1%+0.5%", "packing": "15Gm Lemi" },
        { "id": 5, "product": "Terbinafine Hcl Cream", "strength": "1%", "packing": "20Gm Lemi Tube" },
        { "id": 6, "product": "Choline Salicylate + Lignocaine Gel", "strength": "8.7%", "packing": "10Gm Lemi Tube" },
        { "id": 7, "product": "Calamine + Liquid Paraffin Lotion", "strength": "8%", "packing": "100ml Single" },
        { "id": 8, "product": "Calamine + Liquid Parrafin Lotion", "strength": "8%", "packing": "60ml Single" },
        { "id": 9, "product": "Clindamycin + Nicotinamide Cream", "strength": "1%+4%", "packing": "15Gm Lemi Tube" },
        { "id": 10, "product": "Clotrimazole Soap", "strength": "1%", "packing": "75Gm Single" },
        { "id": 11, "product": "Thiocolchicoside+Diclofenac Diethylamine+Diclofenac Sodium+Linseed Oil+Methyl Salicylate+Menthol Gel", "strength": "0.125%+1.16%+1.0%+3.0%+10.0%+5.0%", "packing": "30G Single" },
        { "id": 12, "product": "Clotrimazole Dusting Powder", "strength": "1%", "packing": "100Gm" },
        { "id": 13, "product": "Diclofenac+Methyl Salicylate+Linseed Oil+Menthol Gel", "strength": "1%+10%+3%+5%", "packing": "30Gm Lemi Tube" },
        { "id": 14, "product": "Diclofenac Diethylamine Topical Spray", "strength": "55G", "packing": "Bottle" },
        { "id": 15, "product": "Aloevera Face Expert", "strength": "120ml", "packing": "Facewash Single" },
        { "id": 16, "product": "Activated Charcoal Facewash", "strength": "60ml", "packing": "Pump Bottle With Golden Neck" },
        { "id": 17, "product": "Enriched With Stearyl Alcohol + Glycerin", "strength": "100ml", "packing": "Single" },
        { "id": 18, "product": "Etoricoxib+Methyl Salicylate+Menthol+Linseed Oil Gel", "strength": "10mg+100mg+50mg+30mg", "packing": "30Gm Lemi Tube" },
        { "id": 19, "product": "Clobetasol Propionate+Neomycin+Miconazole Nitrate Cream", "strength": "0.05%+0.50%+2.00%", "packing": "10Gm Lemi Tube" },
        { "id": 20, "product": "Fluconazole Soap", "strength": "1%", "packing": "75Gm Single" },
        { "id": 21, "product": "Fusidic Acid Cream", "strength": "2%", "packing": "10Gm Lemi Tube" },
        { "id": 22, "product": "Itraconazole+Terbinafine Hydrochloride Cream", "strength": "1.0%+1.0%", "packing": "20Gm Lemi Tube" },
        { "id": 23, "product": "Ketoconazole Cream", "strength": "2%", "packing": "30Gm Lemi Tube" },
        { "id": 24, "product": "Clobetasol Propionate+Gentamycin Sulphate+Tolnaftate+Iodochlorhydroxyquinoline+Clotrimazole Cream", "strength": "0.05%+0.10%+1.00%+1.0%+1.0%", "packing": "15Gm Lemi Tube" },
        { "id": 25, "product": "Ketoconazole+Zinc Pyrithione Soap", "strength": "1%+1%", "packing": "75Gm Single" },
        { "id": 26, "product": "Ketoconazole Soap", "strength": "1%", "packing": "75Gm Single" },
        { "id": 27, "product": "Ketoconazole+Cetrimide Soap", "strength": "1%+0.5%", "packing": "75Gm Single" },
        { "id": 28, "product": "Ketoconazole+ZPTO+D-Panthenol+Biotin+Aloe Vera Extract", "strength": "100ml", "packing": "Pet Bottle" },
        { "id": 29, "product": "Troxerutin+Calcium Dobesilate+Lignocaine Hcl+Hydrocortisone Acetate+Zinc+Phenylephrine Hcl Cream", "strength": "30Gm", "packing": "Lemi Tube" },
        { "id": 30, "product": "Luliconazole Cream", "strength": "1%", "packing": "30Gm Special Window tray pack" },
        { "id": 31, "product": "Luliconazole+Benzyl Alcohol Lotion", "strength": "1%+1%", "packing": "30ml Lotion" },
        { "id": 32, "product": "Mupirocin Ointment", "strength": "2%", "packing": "5Gm Lemi Tube" },
        { "id": 33, "product": "Ofloxacin+Ornindazole+Itraconazole+Clobetasol Propionate Cream", "strength": "0.75%+2.0%+1.0%+0.05%", "packing": "15Gm Lemi Tube" },
        { "id": 34, "product": "Sunscreen Lotion", "strength": "SPF 50", "packing": "60ml Pump Bottle With Golden Neck" },
        { "id": 35, "product": "Povidone Iodine+Metronidazole+Sucralfate Cream", "strength": "5.0%+1.0%+7.0%", "packing": "15Gm Lemi Tube" },
        { "id": 36, "product": "Permethrin+Cetrimide Lotion", "strength": "5.0%+0.1%", "packing": "60ml Single" },
        { "id": 37, "product": "Triclosan+Vitamin E+Allontoin+Tea Tree Oil Soap", "strength": "1%+0.25%+1.0%+0.2%", "packing": "75Gm Single" },
        { "id": 38, "product": "Vaginal Wash", "strength": "100ml", "packing": "Single" }
      ]
    },
    {
      "category": "MISCELLANEOUS PRODUCTS",
      "products": [
        { "id": 1, "product": "Dextrose+Sucrose+Zinc Sulphate+Vitamin C Powder", "strength": "17.5Gm+14Gm+32.5mg+50mg", "packing": "105Gm Pouch Pack" },
        { "id": 2, "product": "Dextrose+Sucrose+Zinc Sulphate+Vitamin C Powder", "strength": "17.5Gm+14Gm+32.5mg+50mg", "packing": "20*1.5 Sachets" },
        { "id": 3, "product": "Cholecalciferol Sachets", "strength": "60,000 IU", "packing": "50*1G Sachets" },
        { "id": 4, "product": "L-Arginine + Proanthocyanidin Granules", "strength": "3Gm+10mg", "packing": "10Gm Sachets" },
        { "id": 5, "product": "Pre & Probiotic With Zinc", "strength": "20*1.5 Sachets", "packing": "" },
        { "id": 6, "product": "Multivitamin+Amino Acids+Caffeine+Ginseng Extract+Zinc Powder", "strength": "5Gm", "packing": "Sachets" },
        { "id": 7, "product": "Amino Acids+Vitamins+Minerals Powder", "strength": "10*5G", "packing": "Sachet" },
        { "id": 8, "product": "Tannic acid+Choline Salicylate+Cetrimide Gum Paint", "strength": "15ml", "packing": "" },
        { "id": 9, "product": "Potassium Nitrate+Sodium Monoflurophosphate+Triclosan Toothpaste", "strength": "5%+0.7%+0.3%", "packing": "100Gm Dental" }
      ]
    },
    {
      "category": "PROTEIN POWDERS",
      "products": [
        { "id": 1, "product": "Protein Powder (Chocolate Elachi Flavour)", "strength": "200Gm", "packing": "Tin Pack" },
        { "id": 2, "product": "Protein Powder With DHA (Chocolate&Elaichi Flavour)", "strength": "200Gm", "packing": "Plastic Pack" },
        { "id": 3, "product": "Protein Booster Enriched With Multivitamin & Multimineral With DHA", "strength": "200Gm", "packing": "Plastic Packing" }
      ]
    },
    {
      "category": "AYURVEDIC PRODUCTS",
      "products": [
        { "id": 1, "product": "Ayurvedic Pain Relief Oil", "strength": "50ml", "packing": "Roll-On Bottle" },
        { "id": 2, "product": "Ayurvedic Pain Relief Oil", "strength": "50ml", "packing": "Pet Bottle" },
        { "id": 3, "product": "Wintergreen Oil+Mahanarayan Oil+Kapoor+Tarpin Oil+Malkagni Oil+Guggal Oil+Mahamash Oil+Panchguna Oil+Pudina Satwa+Mahavishgarbha Oil+Til Oil", "strength": "20%+40%+4%+2%+3%+5%+10%+5%+1%+10%/100ml", "packing": "Spray" },
        { "id": 4, "product": "The Herbal care for joint pain", "strength": "30Caps", "packing": "Pet Bottle" },
        { "id": 5, "product": "Chatpat Appetiser", "strength": "200ml", "packing": "Pet Bottle" },
        { "id": 6, "product": "Sulphur Purified+Centra Therum Antheminiticum+Terbinellia Chebula+Emblica Officinalis", "strength": "90mg+60mg+50mg+50mg", "packing": "30Caps Pet Bottle" },
        { "id": 7, "product": "Ayurvedic Cough Syrup (With Honey)", "strength": "100ml", "packing": "Pet Bottle" },
        { "id": 8, "product": "A Complete Ayurvedic Uterine Syrup", "strength": "200ml", "packing": "Pet Bottle" },
        { "id": 9, "product": "A Herbal Antacid (Suger Free)", "strength": "200ml", "packing": "Pet Bottle" },
        { "id": 10, "product": "A Complete Health Tonic For Women", "strength": "300ml", "packing": "Pet Bottle" },
        { "id": 11, "product": "Amla+Bhringraj+Nagarmotha+Ghritkumari+Shikakai+Jatamasi+Brahmi+Gudhal Pushp+Nagkesar+Heena+Giloy+Yashtimadhu+Harad+Haldi Hair Oil", "strength": "2000mg+4000mg+1000mg+1000mg+1500mg+1000mg+1500mg+2000mg+1000mg+1500mg+1000mg+1000mg+1000mg+1000mg", "packing": "100ml Single" },
        { "id": 12, "product": "Isobgol Husk+Yashtimadhu+Senna+Harad+Kali Mirch+Amaltas+Gulab+Sajjkhar+Ajwain", "strength": "40Gm+5Gm+15Gm+10Gm+5Gm+5Gm+5Gm+5Gm+5Gm", "packing": "100Gm Pet Bottle" },
        { "id": 13, "product": "Neem+Daruharidra+Triphala+Nagkeshwar+Dashmool+Shunthi+Makoya+Sphatika+Kutaki+Mochras+Shudh Guggal+Lajjalu+Yashad Bhasma+Shankh Bhasma Capsule", "strength": "100mg+90mg+60mg+50mg+40mg+20mg+20mg+20mg+20mg+20mg+10mg+10mg+20mg+20mg", "packing": "30Caps Pet Bottle" },
        { "id": 14, "product": "Bhumiamla+Kathumar+Bahera+Chandrika+Hauber+Kutaki+Renuka+Harad+Gulab+Punarnava+Chitrakmool+Daruharidra+Sarfooka+Rohera Liver Tonic", "strength": "300mg+100mg+100mg+100mg+100mg+200mg+100mg+200mg+200mg+250mg+250mg+100mg+100mg+200mg", "packing": "200ml Pet Bottle" },
        { "id": 15, "product": "Liver Tonic With Enzyme Syrup", "strength": "200ml", "packing": "Pet Bottle" },
        { "id": 16, "product": "A Herbal Brain Booster", "strength": "200ml", "packing": "Pet Bottle" },
        { "id": 17, "product": "Ayurvedic Liver Tonic", "strength": "200ml", "packing": "Pet Bottle" },
        { "id": 18, "product": "Rubia Cordifolia+Acacia Catechu+Berberisaristata+Swertia Chirata+Andrographis Paniculata+Fumaria Parvifflora+Terminalia Chebula+Tinospora Cardifolia+Spaeranthus", "strength": "500mg+200mg+200mg+100mg+200mg+200mg+600mg+200mg/200ml", "packing": "Pet Bottle" },
        { "id": 19, "product": "Crataeva Nurvala+Bergenia Ligulata+Processed Alum+Sodium Chloridesalt+Cucumis Sativus+Tribulus Terrestris+Picrorrhiza Kurroa", "strength": "20mg+50mg+80mg+50mg+40mg+40mg+40mg", "packing": "18Caps Pet Bottle" },
        { "id": 20, "product": "Mukta Shukti Bhasma+Godanti Hartall Bhasma+Khatika+Aspartame", "strength": "300mg+100mg+200mg+4mg", "packing": "30 Capsules" },
        { "id": 21, "product": "Aloe Vera+Amla Juice", "strength": "99.8%+99.8%/500ml", "packing": "Pet Bottle" },
        { "id": 22, "product": "Harad+Behra+Amla Juice", "strength": "33%+33%+33%/500ml", "packing": "Pet Bottle" },
        { "id": 23, "product": "Pashanbhed+Ber Pather+Makoy+Nagarmotha+kultha+Gokhru+Punarnav+Manjitha", "strength": "80mg+50mg+50mg+70mg+80mg+40mg+80mg+50mg", "packing": "30 Capsules" },
        { "id": 24, "product": "Majju+Lodhra+Supari+Ashoka+Rall Safaid+Goond Babool+Geru+Aamuthli", "strength": "60mg+60mg+80mg+60mg+60mg+60mg+60mg+60mg", "packing": "31 Capsules" },
        { "id": 25, "product": "Kali mirch+Sarpagandha+Brahmi+Jatamansi+Shankhpushpi+Aswagandha", "strength": "50mg+50mg+150mg+50mg+50mg+50mg", "packing": "30 Capsules" },
        { "id": 26, "product": "Kutaja+Bilwa Maja+Daniharidra+jatiphala+Shankha Bhasma", "strength": "150mg+50mg+50mg+50mg/30", "packing": "Capsules" },
        { "id": 27, "product": "Maju Fal+mai Khurd+Lodhra+Samudra Sokh+Gond Dhak+Shatavari+pigu Fal", "strength": "75mg+75mg+50mg+75mg+75mg+75mg+75mg", "packing": "30 Capsules" },
        { "id": 28, "product": "Sarpagandha+Punarnava+Gokhru+Bhumi Amla+Aswagandha+Jatamansi+Arjuna", "strength": "120mg+40mg+40mg+40mg+40mg+70mg+100mg", "packing": "30 Capsules" },
        { "id": 29, "product": "Gandhak+Somraji+Harad+Amla+Neem+Giloy", "strength": "150mg+150mg+75mg+50mg+50mg+50mg", "packing": "30 Capsules" },
        { "id": 30, "product": "Amla Juice", "strength": "99.8%/500ml", "packing": "Pet Bottle" },
        { "id": 31, "product": "Ashwagandha+Tulsi+Amla+Neem+Turmeric+Satva Gilo+Dalchini", "strength": "100mg+50mg+100mg+50mg+50mg+100mg+50mg", "packing": "30 Capsules" },
        { "id": 32, "product": "Withania Somnifera+Glycyrrhiza glbra+Aspabagus Raacemosus+Boethavia Diffusa+Pueraria Tubeerose+Salmalia Malbarica+Eclipta Alba+Emblica Offcinalis+Pedalium Murax+Terminallia Arjuna", "strength": "90mg+60mg+60mg+60mg+30mg+30mg+30mg+30mg+60mg+30mg", "packing": "30 Capsules" },
        { "id": 33, "product": "Somlata+Mulethi+Dalchini+Vasaka+Tankan Bhasma+Kulanjan", "strength": "85mg+85mg+85mg+75mg+85mg+85mg", "packing": "30 Capsules" }
      ]
    },
    {
      "category": "RESPULES",
      "products": [
        { "id": 1, "product": "Salbutamol Nebuliser Solution", "strength": "2.5mg", "packing": "20*5*2.5ml Respules" },
        { "id": 2, "product": "Budesonide Respules", "strength": "0.5mg", "packing": "4*5*2ml Respules"},
        { "id": 3, "product": "Budesonide( 0.5 ) & Formoterol 20Mcg Fumarate Respirator Suspension", "strength": "0.5mg", "packing": "4*5*2 ml Respules"},
        { "id": 4, "product": "Formoterol Fumarate i.P. 6mcg & Budesonide I.P. 200mcg", "strength": "0.5mg", "packing": "30 Capsules"},
        { "id": 4, "product": "Levosalbutamol Sulphate IP 1.25 mg & Ipratropium Bromide IP 500 mg", "strength": "0.5mg", "packing": "4*5*2.5ml Respules"},
      ]
    }
];

const columns = [
  {
    title: 'S.NO',
    dataIndex: 'id',
    key: 'id',
    width: 80,
  },
  {
    title: 'PRODUCTS',
    dataIndex: 'product',
    key: 'product',
  },
  {
    title: 'STRENGTH',
    dataIndex: 'strength',
    key: 'strength',
    width: 200,
  },
  {
    title: 'Packing',
    dataIndex: 'packing',
    key: 'packing',
    width: 200,
  },
];

export default function ProductsPage() {
  return (
    <div className="">
      <div className="">
        <Breadscrumb items={breadcrumbItems} />
      </div>

      <div className="container mx-auto px-4 py-6">
        <Collapse accordion defaultActiveKey={['1']} className="product-collapse">
          {productsData.map((categoryData, index) => (
            <Panel 
              header={<span className="font-bold text-lg">{categoryData.category}</span>} 
              key={index + 1}
            >
              <Table 
            //@ts-ignore
                dataSource={categoryData.products} 
                columns={columns} 
                bordered
                pagination={{ pageSize: 10, hideOnSinglePage: true }}
                scroll={{ x: true }}
                className="shadow-md"
                rowKey="id"
              />
            </Panel>
          ))}
        </Collapse>
      </div>
    </div>
  );
}